### PR TITLE
Fixed DateTime() typo

### PR DESCRIPTION
**Pull request by stefanos82**
Fixed a typo with `DateTime()` used in functions `date_add()` and `date_sub()` respectively.

### CODE REVIEW

**Review by aaemnnosttv — CHANGES_REQUESTED** [review]
I remember fixing this but it must have been in a separate working branch 😄  Thanks! 

This appears to be missing the `use` statement for `DateTime` above though. This is needed since the code there is in the context of the `WP_SQLite_DB` namespace. Would you please add that? Thanks again 👍

**Comment by stefanos82** [comment]
Darn it, I forgot to add it lol I had it added on my local version, but not on the patched one; my apologies mate.

I'm doing it right now.

**Comment by stefanos82** [comment]
Missing `use DateTime();` has been added.

Can you check it now please?

**Review by aaemnnosttv — APPROVED** [review]
LGTM 👍  Thanks!

**Pull request merged**
